# Generated by Django 5.0.7 on 2024-07-19 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
