# Generated by Django 5.0.7 on 2024-07-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='donar',
            name='work_for',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
