# Generated by Django 5.0.7 on 2024-07-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0003_donar_work_for_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
