# Generated by Django 5.0.7 on 2024-07-27 06:00

import django.db.models.deletion
import moderator.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0004_delete_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('working_area', models.CharField(max_length=70, null=True)),
                ('organization_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('establishing_year', models.DateField()),
                ('logo', models.ImageField(null=True, upload_to=moderator.models.moderatorImgUpload)),
                ('organization_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
