# Generated by Django 5.0.7 on 2024-07-28 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0005_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donar',
            old_name='thana',
            new_name='upazila',
        ),
    ]
